# Image definitions
image:
  repository: ghcr.io/gotify/server
  tag: "{{ .Chart.AppVersion }}"
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        port: 80

workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
          probes:
            readiness:
              enabled: true
              type: http
              path: /health
            liveness:
              enabled: true
              type: http
              path: /health
            startup:
              enabled: true
              type: http
              path: /health

persistence:
  data:
    enabled: true
    mountPath: /app/data
