apiVersion: v2
name: stalwart
description: A secure, scalable, and comprehensive open-source mail server
type: application
version: 0.1.1
appVersion: 0.16.7 # renovate: image=stalwartlabs/stalwart
dependencies:
  - name: common
    version: 29.x.x
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
